### ISSUE TITLE
readme.md describes wrong command to load task

### ISSUE THREAD

**Issue by cniemann** [SafeMarket/grunt-solc-output-deploy#1]
Hi, 

the readme.md describes the npmloadtask as:
`grunt.loadNpmTasks('solc-output-deploy');`

Instead it should say: `grunt.loadNpmTasks('grunt-solc-output-deploy');` (with an added `grunt`).

Then it loads correctly.

**Comment by aakilfernandes** [comment]
Fixed https://github.com/SafeMarket/grunt-solc-output-deploy/commit/ac152606d014aeed0570a513e6cd4c071b3f8698

Thanks!
